name: sample_riverpod
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For Firebase
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  firebase_remote_config: ^0.4.3
  tuple: ^1.0.3

  # For Architecture
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.1

  # For Local Storage
  shared_preferences: ^0.5.12+4



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/white_smoking_icon.png
    - assets/images/frontier_light_icon.png
    - assets/images/marlboro_menthol_light_icon.png
    - assets/images/mild_seven_icon.png
    - assets/images/seven_star_icon.png
    - assets/images/cabin_mild_icon.png

